# MAIN base
baseURL = "https://www.makemonmouth.co.uk/"
languageCode = "en-gb"
title = "Make Monmouth | Monmouth's Community Makerspace"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Membership"
    url = "#membership"
    weight = 3
[[menu.main]]
    name = "FAQ"
    url = "#faq"
    weight = 4
[[menu.main]]
    name = "Login"
    url = "/login"
    weight = 5

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Woodland Stores, Woodland View, Wyesham, NP25 3LD"
email = "info@makemonmouth.co.uk"
#phone = "+(448) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
twitter = "https://twitter.com/static_mania"
github = "https://github.com/StaticMania"

[params]

# Header
logo = "images/MakeMonmouth_Logo_Alt-01_20230920.svg"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Make Monmouth CIC"
copyright1 = "All right reserved"
copyright2 = "&copy; Make Monmouth CIC {year}"

#contact
email = "info@makemonmouth.co.uk"
