[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION="v0.111.1"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true
