[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION="0.111.1"
  GIT_DEPLOY="true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/privacy"
  to   = "https://docs.makemonmouth.co.uk/en/latest/gdpr_notice/"
  status = 301
  force = true
[[redirects]]
  from = "/login"
  to   = "https://members.makemonmouth.co.uk/login"
  status = 301
  force = true
[[redirects]]
  from = "/discord"
  to   = "https://discord.gg/DN8Rup7g4t"
  status = 301
  force = true

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
[[headers]]
    for = "/*.woff2"
    [headers.values]
        Access-Control-Allow-Origin = "*makemonmouth.co.uk"
