[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION="v0.111.1-39a4a3cf676533859217805c36181c7a3dfa321c+extended"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true
